export XDG_CONFIG_HOME=$HOME/.config
export ZDOTDIR=$HOME/.config/zsh
export ENHANCD_DIR=$HOME/.local/share/enhancd
export EDITOR=nvim
export BROWSER=firefox
export LANGUAGE=ja_JP.UTF-8
export LC_ALL=ja_JP.UTF-8
export LANG=ja_JP.UTF-8
export LISTMAX=0 # zshの補完リストが多い時(-1:尋ねない 0:尋ねる)
export PIPENV_VENV_IN_PROJECT=1 # pipenvの環境変数
export VIRTUAL_ENV_DISABLE_PROMPT=1
export RANGER_LOAD_DEFAULT_RC=FALSE
export NVM_DIR="$HOME/.nvm"
export PATH="$HOME/.yarn/bin:$HOME/.config/yarn/global/node_modules/.bin:$PATH"
export PATH=$HOME/bin:$HOME/.local/bin:$PATH
export PATH=$HOME/.local/share/gem/ruby/3.0.0/bin:$PATH
export DENO_INSTALL="$HOME/.deno"
export PATH="$DENO_INSTALL/bin:$PATH"
export BUN_INSTALL="$HOME/.bun"
export PATH="$BUN_INSTALL/bin:$PATH"
