[share]
base = [
  "archlinux-keyring",
  "base-devel",
  "unzip",
  "openssh",
  "python3",
  "python-pip",
  "deno",
  "dosfstools",
]

sound = [
  "sof-firmware",
  "pipewire",
  "pipewire-alsa",
  "pipewire-pulse",
]

network = [
  "netctl",
  "iw",
  "wpa_supplicant",
  "networkmanager",
  "dhcpcd",
]

shell = [
  "zsh",
  "sheldon",
  "fzf",
  "neovim",
  "python-pynvim",
]

shell_tools = [
  "lsd",
  "ranger",
  "neofetch",
  "ueberzug",
  "man-db",
  "man-pages",
  "textinfo",
]

x = [
  "xorg",
  "xorg-xinit",
  "xf86-video-intel",
]

wm = [
  "qtile",
  "picom",
  "rofi",
]

gui_utils = [
  "evince",
  "pavucontrol",
  "gwenview",
  "discord"
]

browser = [
  "firefox",
  "google-chrome",
]

input_method = [
  "fcitx5-im",
  "fcitx5-skk",
]

[wsl]
[not wsl]
base = [
  "docker",
  "efibootmgr",
]
